language: java
script:
 - mvn clean verify --file ./simple-api/pom.xml
 - docker login -u $DOCKERHUB_ID -p $DOCKERHUB_PWD

 - docker-compose up

 - docker tag  project-tp2 $DOCKERHUB_ID/project-tp2:1.0
 - docker push $DOCKERHUB_ID/project-tp2
