language: java
script:
 - cd ./simple-api/
 - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=hugokey
 - cd ..

 - docker login -u $DOCKERHUB_ID -p $DOCKERHUB_PWD

 - docker build -t $DOCKERHUB_ID/project-tp2:database database
 - docker build -t $DOCKERHUB_ID/project-tp2:httpd httpd
 - docker build -t $DOCKERHUB_ID/project-tp2:simple-api simple-api
 - docker build -t $DOCKERHUB_ID/project-tp2:front front

 - docker push $DOCKERHUB_ID/project-tp2:database
 - docker push $DOCKERHUB_ID/project-tp2:httpd
 - docker push $DOCKERHUB_ID/project-tp2:simple-api
 - docker push $DOCKERHUB_ID/project-tp2:simple-api


addons:
 sonarcloud:
  organization: "hugokey"
  token: "$SONARCLOUD_TOKEN"

