language: java
script:
 - mvn clean verify --file ./simple-api/pom.xml org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=hugolerondel_dev-ops

 - docker login -u $DOCKERHUB_ID -p $DOCKERHUB_PWD

 - docker build -t $DOCKERHUB_ID/project-tp2:database database
 - docker build -t $DOCKERHUB_ID/project-tp2:httpd httpd
 - docker build -t $DOCKERHUB_ID/project-tp2:simple-api simple-api

 - docker push $DOCKERHUB_ID/project-tp2:database
 - docker push $DOCKERHUB_ID/project-tp2:httpd
 - docker push $DOCKERHUB_ID/project-tp2:simple-api

addons:
 sonarcloud:
  organization: "hugolerondel"
  token:
   secure: "$SONARCLOUD_TOKEN"

